x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_NAME: ${DATABASE_NAME}
  DATABASE_USERNAME: ${DATABASE_USERNAME}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  SUPABASE_PROJECT_URL: ${SUPABASE_PROJECT_URL}
  SUPABASE_API_KEY: ${SUPABASE_API_KEY}
  TRIPADVISOR_API_KEY: ${TRIPADVISOR_API_KEY}
  EdDSA_PUBLIC_KEY: ${EdDSA_PUBLIC_KEY}
  EdDSA_PRIVATE_KEY: ${EdDSA_PRIVATE_KEY}
  CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
  CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID}
  
services:
  app:
    image: api:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    ports:
      - '8080:8080'
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
