services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  swift-test:
    build:
      context: .
      dockerfile: TestDockerfile
    working_dir: /build
    command: ["swift", "test"]
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      TRIPADVISOR_API_KEY: $TRIPADVISOR_API_KEY
      CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
      CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
