name: Lint

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  lint:
    name: Lint Swift
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Install swiftly
      run: curl -L https://swift-server.github.io/swiftly/swiftly-install.sh | bash -s -- --disable-confirmation
    - name: Install Swift
      run: swiftly install latest
    - name: Show Swift version
      run: swift --version
    - uses: actions/checkout@v4
    - name: Lint
      run: swift package plugin lint-source-code