name: Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-main-jammy
    steps:
      - uses: actions/checkout@v4
      - run: swift format lint -r -p -s .
