name: Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: docker compose run swift-test
        env:
          TRIPADVISOR_API_KEY: ${{ secrets.TRIPADVISOR_API_KEY }}

      - name: Cleanup
        if: always()
        run: docker-compose down
